### ISSUE TITLE
ExceptionsManager.js:61 RawText "0" must be wrapped in an explicit <Text> component.

### ISSUE THREAD

**Issue by liugangfeng** [dwqs/respine#1]
ExceptionsManager.js:61 RawText "0" must be wrapped in an explicit <Text> component.

**Comment by dwqs** [comment]
how did it happen？ can you show me the code?

**Comment by darrenchiu** [comment]
I got the same issue...

**Comment by mataoct** [comment]
I got the same issue...

**Comment by dwqs** [comment]
how did it reproduce?   can you show me the code? @darrenchiu @mataoct

**Comment by mataoct** [comment]
i have the bug in RN  0.39，  and i debug the code,   i will push later,

and,please provide a runnable example, the demo can't be excuted by 'npm install && react-native run-ios'

**Comment by dwqs** [comment]
thx @mataoct
