### ISSUE TITLE
Back Button support

### ISSUE THREAD

**Issue by mykelaballe** [dwqs/respine#3]
Is this repo still maintained? are you able to add a back button support to close the gallery for android phone?

**Comment by sood03** [comment]
@mykelaballe , Back button is not working but you can close the ImageViewer by clicking on the photo when opened in full screen mode.

Maybe we can add this functionality on our own. I was thinking to add a cross icon on top and set onPress to close the view but seems like 

shown 
imageUrls 
onClose 
index 
failedUrl

are the only props allowed for ImageViewer. Need to think for some other way to implement this cross button.

**Comment by mykelaballe** [comment]
i agree. back button is essential for UX especially for android users. ive tested on some android devices, tapping the photo to close it doesnt work

**Comment by hidejjj** [comment]
same issue. some android devices, tapping the photo to close it doesnt work

**Comment by dwqs** [comment]
Add a back button on the top left corner in v2
