### ISSUE TITLE
Add a cancel/cross icon in ImageViewer

### ISSUE THREAD

**Issue by sood03** [dwqs/respine#4]
I am trying to add a cross icon on the top left corner of ImageViewer which would also close the ImageViewer to view image gallery. But the icon doesn't appear.

Following is my snippet of the view showing image gallery

```
openViewer(index){
		this.setState({
			shown:true,
			curIndex:index
		})
	}

closeViewer() {
		this.setState({
			shown: false,
			curIndex: 0
		})
	}

<Content style={styles.container}>
	<View style={styles.containerImage}>
		{
			imgsArr.map((url,index)=>{
				return <TouchableOpacity key={index}
                                         activeOpacity={1}
										 onPress={this.openViewer.bind(this,index)}>
							<Image
								source={{uri: url}}
								style={styles.img}/>
				</TouchableOpacity>
			})
		}
		<Icon
			name="close"
			onPress={() => {
                            this.setState({
									shown: false,
									curIndex: 0
								});
							}}
			style={{marginLeft:0, marginTop:0, color: "white"}}
		/>
		<ImageViewer shown={this.state.shown}
					 imageUrls={imgsArr}
					 onClose={this.closeViewer.bind(this)}
					 index={this.state.curIndex}>

		</ImageViewer>
	</View>
</Content>
```

**Comment by hidejjj** [comment]
modalDismissed(){
        if (this.props.shown){
            this.props.onClose();
        }
    }

<Animated.View style={[viewer.titleBar,{
                    opacity:this.state.fadeAnim, flexDirection:'row'
                }]}>
                    <Text style={viewer.title}>
                        {(this.state.curIndex + 1)} / {this.props.imageUrls.length}
                    </Text>
                    <Text style={[viewer.title,{marginLeft:50,textAlign:'right'}]} onPress={this.modalDismissed.bind(this)}>Close</Text>
                </Animated.View>

**Comment by dwqs** [comment]
Add a back button on the top left corner in v2
