### ISSUE TITLE
bundling failed: ReferenceError: Unknown plugin "transform-react-remove-prop-types"

### ISSUE THREAD

**Issue by memanoj** [dwqs/respine#6]
after install react-native-image-viewer i am facing this issue how can i resolve it bundling failed: ReferenceError: Unknown plugin "transform-react-remove-prop-types"

**Comment by dwqs** [comment]
Try npm i babel-plugin-transform-react-remove-prop-types -D in your project

**Comment by memanoj** [comment]
it's working with reinstall app thank you
